apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  my-app
  namespace: react
spec:
  project: default
  source:
    repoURL: 'https://github.com/my-appv3.git'
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: react
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
