name: CI/CD Pipeline for React v3

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy-v3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image for my-appv
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64  # Multi-platform build
        context: .  # Use "." if Dockerfile is in the root directory
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ github.run_id }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest
    - name: SSH into server and deploy my-app to Docker Swarm
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          IMAGE_TAG=${{ github.run_id }}
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$IMAGE_TAG
          
          # ✅ Ensure the Docker network exists
          docker network ls | grep -q "my_network" || docker network create --driver overlay my_network
          # ✅ Deploy or update the my-app service
          if ! docker service ls | grep -q "my-appv3"; then
            docker service create \
              --name my-app \
              --replicas 2 \
              --publish 8080:80 \
              --network my_network \
              ${{ secrets.DOCKER_HUB_USERNAME }}/my-appv3:$IMAGE_TAG
          else
            docker service update --image ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$IMAGE_TAG my-appv3
          fi