name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push version v3
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:v3-${{ github.run_id }}

      - name: SSH to Server and Deploy v3
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the updated v3 frontend image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:v3-${{ github.run_id }}

            # Remove the old service if it exists
            docker service rm frontend-v3 || true

            # Create a new service using docker service create and attach it to the existing terminal-network
            docker service create \
              --name frontend-v3 \
              --replicas 2 \
              --network terminal-network \
              -p 8080:80 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:v3-${{ github.run_id }}

            # Optionally prune unused Docker volumes and networks
            docker system prune -f --volumes

