name: Deploy v3 application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/terminal_frontend:${{ github.run.id }}

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            docker network create --driver overlay terminal-network || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/terminal_frontend:${{ github.run.id }}
            docker service create \
              --name terminal_frontend \
              --replicas 2 \
              -p 8080:80 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/terminal_frontend:${{ github.run.id }}
            docker system prune -f --volumes
