name: Rollback to v3

on:
  workflow_dispatch:  # Allows manual rollback trigger

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
    
    # ✅ Step 1: Connect to Remote Server and Rollback to v3
    - name: Rollback to v3 on Docker Swarm
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "🔄 Rolling back to v3..."
          
          # ✅ Ensure v3 image is available
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-appv3:latest

          # ✅ Update the running service to v3
          docker service update --image ${{ secrets.DOCKER_HUB_USERNAME }}/my-appv3:latest my-app
          
          # ✅ Wait for rollback to complete
          sleep 20
          
          # ✅ Verify the rollback
          if docker service ps my-app --format "{{.CurrentState}}" | grep -q "Running"; then
            echo "✅ Rollback to v3 successful!"
          else
            echo "❌ Rollback failed!"
            exit 1
          fi
