name: Deploy v3 application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 3. Build and Push Docker Image to Docker Hub
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64  # Corrected 'platform' to 'platforms'
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/terminal_frontend:${{ github.run.id }}  # Corrected tag format
          load: false
          no-cache: false
          pull: false

      # 4. SSH to Server and Deploy
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 4.1 Create Docker Swarm network if it doesn't exist
            docker network create --driver overlay terminal-network || true

            # 4.2 Pull the Docker image from Docker Hub
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/terminal_frontend:${{ github.run.id }}

            # 4.3 Create a Docker service in Swarm mode (2 replicas)
            docker service create \
              --name terminal_frontend \
              --replicas 2 \
              -p 8080:80 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/terminal_frontend:${{ github.run.id }}

            # 4.4 Clean up unused Docker objects (volumes, containers, images)
            docker system prune -f --volumes
