name: Rollback to v3

on:
  workflow_dispatch  # Manually trigger rollback from GitHub Actions UI

jobs:
  rollback-to-v3:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into server and rollback to v3
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-appv3:latest
          
          # ✅ Ensure the Docker network exists
          docker network ls | grep -q "my_network" || docker network create --driver overlay my_network
          
          # ✅ Rollback to v3
          docker service update \
            --image ${{ secrets.DOCKER_HUB_USERNAME }}/my-appv3:latest \
            my-appv3
          
          # ✅ Verify rollback was successful
          docker service ps my-appv3
