name: Rollback to v5

on:
  push:
    branches:
      - rollback-to-v5  # Trigger workflow when rollback branch is pushed

jobs:
  rollback-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: SSH into server and rollback to v5
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Define the rollback image with the correct tag
          ROLLBACK_IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/my-app:13629419604"

          echo "Rolling back to previous version: $ROLLBACK_IMAGE"

          # Pull the previous version
          docker pull $ROLLBACK_IMAGE

          # Update Docker Swarm service to rollback to v5
          docker service update --image $ROLLBACK_IMAGE my-app
