name: CI/CD Pipeline for React v4

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy-v4:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image for my-appv4
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64  # Multi-platform build
        context: .  # Use "." if Dockerfile is in the root directory
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/my-appv4:${{ github.run_id }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/my-appv4:latest

    - name: SSH into server and update service to v4
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          IMAGE_TAG=${{ github.run_id }}
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-appv4:$IMAGE_TAG
          
          # ✅ Ensure the Docker network exists
          docker network ls | grep -q "my_network" || docker network create --driver overlay my_network
          
          # ✅ Immediate service update to v4
          docker service update \
            --image ${{ secrets.DOCKER_HUB_USERNAME }}/my-appv4:$IMAGE_TAG \
            my-appv3
          
          # ✅ Verify the update was successful
          docker service ps my-appv3
